### ISSUE TITLE
Undefined venue

### ISSUE THREAD

**Issue by daniddelrio** [compsat/ls-ganap#117]
If the event has a venue within Ateneo (i.e. it doesn't use outside_venue_name), the venues of the event are undefined, so the venue doesn't show. 

I traced it, and it's when I remove the EventHorizontalScroller in the old code that it doesn't work. When I put it back, the venues appear. When I logged in the console the venues of the event, it becomes undefined.

**Comment by galacemiguel** [comment]
Very very bizarre bug and it took me a **long** time to track it down.

Turned out to have been a mutation issue. Can concretely see now why it's said to be bad practice. Too lazy to make a PR now, but the fix is basically to replace [the `pickEventLogistics` method in `eventsSelectors.js`](https://github.com/compsat/ls-ganap/blob/master/client/src/selectors/eventsSelectors.js#L41-L46) with this:
```javascript
pickEventLogistics() {
  return this.event.event_logistics.map(eventLogistics => ({
    ...eventLogistics,
    venue: this.venues[eventLogistics.venue]
  }));
}
```

Can you test for yourself and make the PR if it works for you?
